server:
  port: 8083
spring:
  application:
    name: Springcloudserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lakshmidedeepya/config.git
          username: lakshmidedeepya
          password: Om$airam9
          clone-on-start: false
         
